### ISSUE TITLE
Document how to use the Eligibility API

### ISSUE THREAD

**Issue by afeld** [cal-itp/eligibility-api#51]
[The docs](https://docs.calitp.org/eligibility-api/) are great at explaining [the specification](https://docs.calitp.org/eligibility-api/specification/), but it's not clear to me how to implement an Eligibility API using this package.

## Acceptance criteria

- [ ] Instructions for installing with `pip`
- [ ] Usage of the [`Client` class](https://github.com/cal-itp/eligibility-api/blob/main/eligibility_api/client.py#L18)
- [ ] Usage of the [`server` helpers](https://github.com/cal-itp/eligibility-api/blob/main/eligibility_api/server.py)

**Comment by thekaveman** [comment]
Note this package is still only half of the implementation - we have cal-itp/eligibility-server#38 to finish out the server side of things.

And then #22 to make this a _real_ package!
