### ISSUE TITLE
Set up workflows to add issues and dependabot PRs to Project

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-api#56]
@machikoyasuda @angela-tran this can be set up easily with our workflow templates:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/1783439/205740870-33955181-0189-4518-8a1a-ce7bff26fd98.png">

From https://github.com/cal-itp/.github/tree/main/workflow-templates

_Originally posted by @thekaveman in https://github.com/cal-itp/eligibility-api/issues/41#issuecomment-1338149192_

**Comment by thekaveman** [comment]
We don't get enough issues/PRs in this repository to worry about this automation right now.
